/** @deprecated Import from `@/components/journal/journal-editorial-icons` */
export {
  JOURNAL_EDITORIAL_CHECK_ICON as EVERGREEN_GUIDE_CHECK_ICON,
  JOURNAL_EDITORIAL_FAQ_CHEVRON as EVERGREEN_GUIDE_FAQ_CHEVRON,
  JOURNAL_EDITORIAL_QUICK_ICON as EVERGREEN_GUIDE_QUICK_ICON,
  JOURNAL_EDITORIAL_SAVE_ICON as EVERGREEN_GUIDE_SAVE_ICON,
  JOURNAL_EDITORIAL_SCENT_ICON as EVERGREEN_GUIDE_SCENT_ICON,
  JOURNAL_EDITORIAL_SHARE_ICON as EVERGREEN_GUIDE_SHARE_ICON,
  JOURNAL_EDITORIAL_TOC_ICON as EVERGREEN_GUIDE_TOC_ICON,
} from "@/components/journal/journal-editorial-icons";
